### ISSUE TITLE
2 urls

### ISSUE THREAD

**Issue by gladiator2b** [jaypalrana/Flutter_Audio_Player#1]
hi,
would it be possible to put 2 urls if how to do please

**Comment by jaypalrana** [comment]
I am not sure how you want to use 2 URLs.
But it is possible if you want to play the second URL audio after the first URL audio got completed.

**Comment by gladiator2b** [comment]
Hi, I would like to have several radios with buttons.
Each button will have a link to a radio

**Comment by jaypalrana** [comment]
You can edit "`audio_player_screen.dart`" and add multiple buttons and multiple URLs.
Also, you need to pass button respective URL in "`playPlayer(url, "Description", "Title").then((value) {});`" method call.

**Comment by gladiator2b** [comment]
hello, thank you very much here it's great
