### ISSUE TITLE
How to stop a music track and start new one ?

### ISSUE THREAD

**Issue by FarhanSaikh** [jaypalrana/Flutter_Audio_Player#3]
As I am adding a queue of music list to choose and when user clicks on it that music will be played.
But the issue is IOS lock screen music controller is not working.
Please guide and  give some documentation.

**Comment by jaypalrana** [comment]
We have added actions on lock screen forward and backward button clicks.
To handle it from your side you need to implement your code in AppDelegate.swift located in iOS folder of source code.
To play the next audio you need to add "nextTrackCommand.addTarget" code in setBackgroundControlls method.
